version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: monthly
    labels:
      - "Building"
    #reviewers:
    #  - carstene1ns
    commit-message:
      prefix: "CI"
