name: Stable Compilation

on:
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      git-ref:
        description: Git Ref (Optional)
        required: false

defaults:
  run:
    shell: bash

jobs:
  docker:
    name: ${{ matrix.image }}
    runs-on: ubuntu-latest
    container:
      image: ${{ matrix.image }}

    strategy:
      fail-fast: false
      matrix:
        image:
          #- debian:10     # oldstable | CMake 3.13.4 | G++ 8.3.0  | SDL 2.0.9
          #- ubuntu:20.04  # LTS       | CMake 3.16.3 | G++ 9.3.0  | SDL 2.0.10
          #- debian:11     # stable    | CMake 3.18.4 | G++ 10.2.1 | SDL 2.0.14
          - ubuntu:22.04  # LTS       | CMake 3.22.1 | G++ 11.2.0 | SDL 2.0.20

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.8.0

      - name: Install dependencies
        run: |
          export DEBIAN_FRONTEND="noninteractive"
          apt-get update
          apt-get install -yqq --no-install-recommends --no-install-suggests \
            ca-certificates build-essential cmake ninja-build git \
            libicu-dev libexpat1-dev libsdl2-dev libpng-dev libpixman-1-dev \
            libfmt-dev libfreetype6-dev libharfbuzz-dev libmpg123-dev \
            libsndfile-dev libvorbis-dev libopusfile-dev libspeexdsp-dev \
            libdrm-dev libgbm-dev # only needed for sdl2 on debian 11

      - name: Clone Repository
        uses: actions/checkout@v2
        if: github.event.inputs.git-ref == ''
      - name: Clone Repository (with custom ref)
        uses: actions/checkout@v2
        if: github.event.inputs.git-ref != ''
        with:
          ref: ${{ github.event.inputs.git-ref }}

      - name: Compile
        run: |
          VER="(GA, `date +%Y-%m-%d`)"
          cmake -G Ninja -B build . \
            -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr \
            -DPLAYER_MULTIPLAYER=on -DPLAYER_BUILD_LIBLCF=on \
            -DPLAYER_VERSION_APPEND="$VER"
          cmake --build build

      - name: Install
        run: |
          # cmake < 3.16 does not support '--install'
          cmake --build build --target install

      - name: Test
        run: |
          # make sure executable runs
          build/easyrpg-player --version
          # run unit tests
          cmake --build build --target check
